services:
  macos:
    image: dockurr/macos
    container_name: macos
    environment:
      VERSION: "14"
      WEB_PORT: "2500"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 2500:2500
      - 5900:5900/tcp
      - 5900:5900/udp
    volumes:
      - ./macos:/storage
    restart: always
    stop_grace_period: 2m
